# Spring Security Configuration

# Server Configuration
#server:
#  port: 8084

# Database Configuration
#spring:
 # datasource:
 #   url: jdbc:mysql://localhost:3306/TableServices
 #   username: root
 #   password: ABC12345abc
  #  driver-class-name: com.mysql.cj.jdbc.Driver

 # jpa:
  #  hibernate:
  #    ddl-auto: update
  #    show-sql: true
  #  properties:
   #   hibernate:
    #    dialect: org.hibernate.dialect.MySQL8Dialect
